# Generated by Django 4.1.1 on 2022-11-14 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("year", models.CharField(blank=True, max_length=20, null=True)),
                ("major", models.CharField(blank=True, max_length=50, null=True)),
                ("minor", models.CharField(blank=True, max_length=50, null=True)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                ("notes", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        default="uploads/profile_pictures/default.png",
                        upload_to="uploads/profile_pictures",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="", max_length=80)),
                ("section", models.TextField(default="", max_length=5)),
                ("topic", models.TextField(default="", max_length=80)),
                ("component", models.TextField(default="", max_length=5)),
                ("units", models.TextField(default="", max_length=1)),
                ("instructor", models.TextField(default="", max_length=30)),
                ("days", models.TextField(default="", max_length=10)),
                ("times", models.TextField(default="", max_length=30)),
                ("location", models.TextField(default="", max_length=30)),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="googleauthentication.timetable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField(default="", max_length=500)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "associated_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to="googleauthentication.timetable",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friends_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "friend_username",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="googleauthentication.userprofile",
                    ),
                ),
            ],
            options={"unique_together": {("user_id", "friends_id")},},
        ),
    ]
