# Generated by Django 4.1.1 on 2022-11-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("googleauthentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friends",
            name="friend_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="googleauthentication.userprofile",
            ),
            preserve_default=False,
        ),
    ]
