# Generated by Django 4.1.1 on 2022-11-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("googleauthentication", "0002_friends_friend_profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="friends", unique_together=set(),),
    ]
