# Generated by Django 4.1.1 on 2022-11-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("googleauthentication", "0003_alter_friends_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friends", unique_together={("user_id", "friends_id")},
        ),
    ]
